AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-course-ordersapi

  Sample SAM Template for lambda-course-ordersapi

Globals:
  Function:
    # These properties will be applied to all Function resources defined below
    Runtime: java11
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    # Creates a new DynamoDB table
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri corresponds to the subdirectory where the Java code lives within this project
      CodeUri: ordersapi
      # Fully qualified path to function name with Java class
      Handler: org.jimtough.aws.lambda.apis.CreateOrderLambda::createOrder
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        # The block below will cause a new API Gateway to be generated by SAM
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
            
  ReadOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      # CodeUri corresponds to the subdirectory where the Java code lives within this project
      CodeUri: ordersapi
      # Fully qualified path to function name with Java class
      Handler: org.jimtough.aws.lambda.apis.ReadOrdersLambda::getOrders
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        # The block below will cause a new API Gateway to be generated by SAM
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET

Outputs:
  CreateOrdersAPI:
    Description: "API Gateway endpoint for Create Orders function"
    # example: https://kckjt232d1.execute-api.us-east-1.amazonaws.com/Prod/orders"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
    